exports.infohypx = (id, BotName, corohelp, tampilTanggal, tampilWaktu, instagramlu, whatsapplu, kapanbotaktif, grupch1, grupch2) => {
	return `🔰 -----[ *INFO HYPIXTRY* ]----- 🔰

• CARA VOTE
- 1. BUKAK LINK https://bit.ly/3hh7AW0
- 2. MASUKAN GEMERTAG KALIAN
- 3. TERUS CLICK AKU BUKAN ROBOT
- 4. CLICK VOTE/SUMBIT/OK
- 5. MASUK KE SERVER HYPIXTRY PILIH VIVA SMP
- 6. SETELAH ITU KETIK /vote DAN NIKMATI LAH HADIAH NYA

• CARA MASUK KE SERVER
- 1. MASUK KE AKUN XBOX
- 2. WORLD | TEMAN | SERVER KALIAN PILIH SERVER
- 3. TRUS ADD SERVER
- 4. MASUKAN NAME SERVER IP SERVER AND PORT SERVER
- 5. SETELAH ITU JOIN

• CARA KEMBALI KE SPAWN VIVA SMP
- 1. BUKK CHAT
- 2. KETIK /pohon TERUS SUMBIT


🔰 -----[ *INFO HYPIXTRY* ]----- 🔰
}
